# Generated by Django 3.0.4 on 2020-04-13 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(default='rhswarriors', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchup.Speech')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchup.User')),
            ],
        ),
    ]
