# Generated by Django 2.1.4 on 2019-01-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('speaker', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=300)),
                ('division', models.CharField(max_length=300)),
                ('score', models.IntegerField(max_length=300)),
            ],
        ),
    ]
