# Generated by Django 2.1.4 on 2019-01-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0002_auto_20190106_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='score',
            field=models.FloatField(),
        ),
    ]
